AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - node_modules/**/*
    - !ruby/regexp /schema\.rb$/
    - db/migrate/*.rb

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc']
  IgnoredMethods: ['describe', 'context']
  Max: 20

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude: ['**/*.rake', '**/*_spec.rb']

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
