AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - node_modules/**/*
    - gemfiles/**/*
    - db/migrate/*.rb
    - bin/*

Layout/LineLength:
  Max: 120

Naming/PredicateName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 16

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  CountAsOne: ["array", "heredoc"]
  Max: 15

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/OpenStructUse:
  Exclude: ["**/*_spec.rb"]
