# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

<% if Rails.application.config.database == :postgres %>
default: &default
  adapter: postgresql
  host: '127.0.0.1'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dummy
  password: postgres
development:
  <<: *default
  database: rmp_dummy_development
test:
  <<: *default
  database: rmp_dummy_test
production:
  <<: *default
  database: rmp_dummy_production
<% else %>
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: db/development.sqlite3
test:
  <<: *default
  database: db/test.sqlite3
production:
  <<: *default
  database: db/production.sqlite3
<% end %>